### ISSUE TITLE
Number of function arguments is wrong in MacOS

### ISSUE THREAD

**Issue by shirk3y** [grn/bash-ctx#7]
When I print `$#`, I receive this output:

```
$ ctx new myctx
1
Error: invalid invocation; expected: ctx new <context name>
```

Is this only Mac related?

**Comment by gregnavis** [comment]
At what precise location in the source code did you print `$#`?

**Comment by gregnavis** [comment]
I'm closing because of not enough detail. Feel free to reopen and share more about the problem.
